sudo: required

language: java
jdk:
  - openjdk10

services:
  - docker

addons:
  apt:
    sources:
      - heroku
    packages:
      - heroku-toolbelt

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
    $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - chmod +x gradlew

script:
  - "./gradlew stage"
  - docker login --username=_ --password="$HEROKU_API_KEY" registry.heroku.com
  - docker build -t registry.heroku.com/$APP_NAME/web .
  - docker push registry.heroku.com/$APP_NAME/web