sudo: required

language: java
jdk:
  - openjdk10

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
    $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

install: true

# TODO: change in git commit
before_script:
  - chmod ugo+x gradlew

script:
  - "./gradlew stage"

# TODO: change in git commit
before_deploy:
  - chmod ugo+x deployment/build-and-push.sh

deploy:
  provider: script
  script: bash deployment/build-and-push.sh
  on:
    branch: master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"