server:
  port: ${PORT:5000}
spring:
  http:
    converters:
      preferred-json-mapper: gson
  datasource:
    url: jdbc:postgresql://${SPRING_DATABASE_HOST}:5432/${SPRING_DATABASE_NAME}?ssl=true&sslmode=require&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: ${SPRING_DATABASE_USER}
    password: ${SPRING_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
